name: "Terraform Create Basic Infrastructure"

on:
  push:
    branches:
      - main
      - terraform
    paths:
      - "terraform/aws/basic-infra/**"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Use Terraform to create basic infrastructure"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Terraform Init"
        working-directory: terraform/aws/basic-infra
        run: terraform init

      - name: "Terraform Format"
        working-directory: terraform/aws/basic-infra
        run: terraform fmt -check

      - name: "Terraform Validate"
        working-directory: terraform/aws/basic-infra
        run: terraform validate

      - name: "Terraform Plan"
        working-directory: terraform/aws/basic-infra
        run: terraform plan

      - name: "Terraform Apply"
        working-directory: terraform/aws/basic-infra
        run: terraform apply -auto-approve