name: "Terraform Create Basic Infrastructure v2"

on:
  push:
    branches:
      - main
      - terraform
    paths:
      - "terraform/aws/basic-infra/**"

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.11.0"
  TF_WORKING_DIR: terraform/aws/basic-infra

jobs:
  terraform:
    name: "Use Terraform to create basic infrastructure"
    runs-on: ubuntu-latest

    # Fallback to 'dev' when triggered by git push instead of workflow_dispatch
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Terraform Init"
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: "Terraform Format"
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: "Terraform Validate"
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: "Terraform Plan"
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }} # Evaluates AFTER environment binding
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: "Terraform Apply"
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply tfplan